<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>MDL.Serializer</RootNamespace>
    <PackageId>Koftamainee.MDL.Serializer</PackageId>
    <Version>1.2.1</Version>
    <Authors>koftamainee</Authors>
    <Company>koftamainee</Company>
    <Description>Reflection-based deserializer mapping MDL documents to CLR objects.</Description>
    <PackageTags>mdl;mantle;data-language;serializer;deserializer</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/koftamainee/mdl</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MDL.Core\MDL.Core.csproj"/>
    <ProjectReference Include="..\MDL.Parser\MDL.Parser.csproj"/>
  </ItemGroup>
</Project>
