<?xml version="1.0"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MDL.Content.Pipeline</RootNamespace>
    <PackageId>Koftamainee.MDL.Content.Pipeline</PackageId>
    <Version>1.2.1</Version>
    <Authors>koftamainee</Authors>
    <Company>koftamainee</Company>
    <Description>MonoGame content pipeline extension (importer/processor/writer) for MDL files.</Description>
    <PackageTags>mdl;mantle;monogame;content-pipeline;importer;processor</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/koftamainee/mdl</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework" Version="3.8.5.1"/>
    <PackageReference Include="MonoGame.Framework.Content.Pipeline" Version="3.8.5.1"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MDL.Core\MDL.Core.csproj"/>
    <ProjectReference Include="..\MDL.Parser\MDL.Parser.csproj"/>
  </ItemGroup>
</Project>
