<?xml version="1.0"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MDL.Content</RootNamespace>

    <PackageId>Koftamainee.MDL.Content</PackageId>
    <Version>1.0.0</Version>
    <Authors>koftamainee</Authors>
    <Company>koftamainee</Company>
    <Description>MonoGame runtime content reader for MDL documents.</Description>
    <PackageTags>mdl;mantle;monogame;content;reader</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/koftamainee/mdl</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework" Version="3.8.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MDL.Core\MDL.Core.csproj" />
  </ItemGroup>
</Project>
