<?xml version="1.0"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>MDL.Core</RootNamespace>
    <PackageId>Koftamainee.MDL.Core</PackageId>
    <Version>1.2.1</Version>
    <Authors>koftamainee</Authors>
    <Company>koftamainee</Company>
    <Description>Core data model for the MDL (Mantle Data Language) parser.</Description>
    <PackageTags>mdl;mantle;data-language;parser;core</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/koftamainee/mdl</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
</Project>
