/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_key = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  sym_number = 6,
  sym_boolean = 7,
  sym_string = 8,
  sym_raw_string = 9,
  sym_bare_string = 10,
  sym_comment = 11,
  sym_source_file = 12,
  sym_pair = 13,
  sym__value = 14,
  sym_object = 15,
  sym_list = 16,
  aux_sym_source_file_repeat1 = 17,
  aux_sym_list_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_key] = "key",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_raw_string] = "raw_string",
  [sym_bare_string] = "bare_string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_pair] = "pair",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_list] = "list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_key] = sym_key,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_raw_string] = sym_raw_string,
  [sym_bare_string] = sym_bare_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_pair] = sym_pair,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_list] = sym_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 15,
  [18] = 18,
  [19] = 10,
  [20] = 8,
  [21] = 9,
  [22] = 11,
  [23] = 23,
};

static const TSCharacterRange sym_bare_string_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'$', 'Z'}, {'\\', '\\'}, {'^', '_'}, {'a', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 2,
        '#', 38,
        '-', 33,
        '[', 11,
        ']', 12,
        '`', 3,
        'f', 20,
        't', 26,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 38,
        '-', 33,
        '[', 11,
        ']', 12,
        '`', 3,
        'f', 21,
        't', 27,
        '{', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '`') ADVANCE(18);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '`') ADVANCE(19);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '}') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_key);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_raw_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_raw_string);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '`') ADVANCE(18);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'a') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'a') ADVANCE(25);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'e') ADVANCE(16);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'l') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'l') ADVANCE(29);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'r') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'r') ADVANCE(31);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 's') ADVANCE(23);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'u') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'u') ADVANCE(23);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_bare_string);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_raw_string] = ACTIONS(1),
    [sym_bare_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(23),
    [sym_pair] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_key] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__value] = STATE(3),
    [sym_object] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_list_repeat1] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_boolean] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_raw_string] = ACTIONS(15),
    [sym_bare_string] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__value] = STATE(4),
    [sym_object] = STATE(4),
    [sym_list] = STATE(4),
    [aux_sym_list_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_boolean] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_raw_string] = ACTIONS(21),
    [sym_bare_string] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__value] = STATE(4),
    [sym_object] = STATE(4),
    [sym_list] = STATE(4),
    [aux_sym_list_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(28),
    [anon_sym_RBRACK] = ACTIONS(31),
    [sym_number] = ACTIONS(33),
    [sym_boolean] = ACTIONS(33),
    [sym_string] = ACTIONS(33),
    [sym_raw_string] = ACTIONS(33),
    [sym_bare_string] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__value] = STATE(6),
    [sym_object] = STATE(6),
    [sym_list] = STATE(6),
    [aux_sym_list_repeat1] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_number] = ACTIONS(41),
    [sym_boolean] = ACTIONS(41),
    [sym_string] = ACTIONS(41),
    [sym_raw_string] = ACTIONS(41),
    [sym_bare_string] = ACTIONS(43),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__value] = STATE(4),
    [sym_object] = STATE(4),
    [sym_list] = STATE(4),
    [aux_sym_list_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(45),
    [sym_number] = ACTIONS(21),
    [sym_boolean] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_raw_string] = ACTIONS(21),
    [sym_bare_string] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__value] = STATE(18),
    [sym_object] = STATE(18),
    [sym_list] = STATE(18),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(49),
    [sym_number] = ACTIONS(51),
    [sym_boolean] = ACTIONS(51),
    [sym_string] = ACTIONS(51),
    [sym_raw_string] = ACTIONS(51),
    [sym_bare_string] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_bare_string,
    ACTIONS(55), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [16] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_bare_string,
    ACTIONS(59), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [32] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_bare_string,
    ACTIONS(63), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [48] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_bare_string,
    ACTIONS(67), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [64] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_key,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [79] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(12), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [93] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    STATE(15), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [121] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [135] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [149] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      sym_key,
      anon_sym_RBRACE,
  [158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      sym_key,
      anon_sym_RBRACE,
  [167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      sym_key,
      anon_sym_RBRACE,
  [176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      sym_key,
      anon_sym_RBRACE,
  [185] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 3,
      ts_builtin_sym_end,
      sym_key,
      anon_sym_RBRACE,
  [194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 16,
  [SMALL_STATE(10)] = 32,
  [SMALL_STATE(11)] = 48,
  [SMALL_STATE(12)] = 64,
  [SMALL_STATE(13)] = 79,
  [SMALL_STATE(14)] = 93,
  [SMALL_STATE(15)] = 107,
  [SMALL_STATE(16)] = 121,
  [SMALL_STATE(17)] = 135,
  [SMALL_STATE(18)] = 149,
  [SMALL_STATE(19)] = 158,
  [SMALL_STATE(20)] = 167,
  [SMALL_STATE(21)] = 176,
  [SMALL_STATE(22)] = 185,
  [SMALL_STATE(23)] = 194,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mdl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
