/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_key_token1 = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  sym_number = 6,
  sym_boolean = 7,
  sym_string = 8,
  sym_raw_string = 9,
  sym_bare_string = 10,
  sym_comment = 11,
  sym_source_file = 12,
  sym_pair = 13,
  sym_key = 14,
  sym__value = 15,
  sym_object = 16,
  sym_list = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_list_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_key_token1] = "key_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_raw_string] = "raw_string",
  [sym_bare_string] = "bare_string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_pair] = "pair",
  [sym_key] = "key",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_list] = "list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_key_token1] = aux_sym_key_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_raw_string] = sym_raw_string,
  [sym_bare_string] = sym_bare_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_pair] = sym_pair,
  [sym_key] = sym_key,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_list] = sym_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_key_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 2,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 14,
  [19] = 19,
  [20] = 12,
  [21] = 10,
  [22] = 11,
  [23] = 9,
  [24] = 24,
};

static const TSCharacterRange sym_bare_string_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'$', 'Z'}, {'\\', '\\'}, {'^', '_'}, {'a', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 2,
        '#', 38,
        '-', 33,
        '[', 11,
        ']', 12,
        '`', 3,
        'f', 20,
        't', 26,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 38,
        '-', 33,
        '[', 11,
        ']', 12,
        '`', 3,
        'f', 21,
        't', 27,
        '{', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '`') ADVANCE(18);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '`') ADVANCE(19);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '`') ADVANCE(3);
      if (lookahead == '}') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_key_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_raw_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_raw_string);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '`') ADVANCE(18);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'a') ADVANCE(25);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'e') ADVANCE(16);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'l') ADVANCE(29);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'r') ADVANCE(31);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 's') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 's') ADVANCE(23);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'u') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'u') ADVANCE(23);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_bare_string);
      if ((!eof && set_contains(sym_bare_string_character_set_1, 9, lookahead))) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_key_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_raw_string] = ACTIONS(1),
    [sym_bare_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym_pair] = STATE(15),
    [sym_key] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_key_token1] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
    [sym_raw_string] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__value] = STATE(4),
    [sym_object] = STATE(4),
    [sym_list] = STATE(4),
    [aux_sym_list_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_boolean] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_raw_string] = ACTIONS(15),
    [sym_bare_string] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__value] = STATE(5),
    [sym_object] = STATE(5),
    [sym_list] = STATE(5),
    [aux_sym_list_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_boolean] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_raw_string] = ACTIONS(21),
    [sym_bare_string] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__value] = STATE(5),
    [sym_object] = STATE(5),
    [sym_list] = STATE(5),
    [aux_sym_list_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(21),
    [sym_boolean] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_raw_string] = ACTIONS(21),
    [sym_bare_string] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__value] = STATE(5),
    [sym_object] = STATE(5),
    [sym_list] = STATE(5),
    [aux_sym_list_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(30),
    [anon_sym_RBRACK] = ACTIONS(33),
    [sym_number] = ACTIONS(35),
    [sym_boolean] = ACTIONS(35),
    [sym_string] = ACTIONS(35),
    [sym_raw_string] = ACTIONS(35),
    [sym_bare_string] = ACTIONS(38),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__value] = STATE(3),
    [sym_object] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_list_repeat1] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(41),
    [sym_number] = ACTIONS(43),
    [sym_boolean] = ACTIONS(43),
    [sym_string] = ACTIONS(43),
    [sym_raw_string] = ACTIONS(43),
    [sym_bare_string] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__value] = STATE(19),
    [sym_object] = STATE(19),
    [sym_list] = STATE(19),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(49),
    [sym_number] = ACTIONS(51),
    [sym_boolean] = ACTIONS(51),
    [sym_string] = ACTIONS(51),
    [sym_raw_string] = ACTIONS(51),
    [sym_bare_string] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(7), 1,
      sym_key,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(8), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
    ACTIONS(57), 3,
      aux_sym_key_token1,
      sym_string,
      sym_raw_string,
  [20] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym_bare_string,
    ACTIONS(60), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [36] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_bare_string,
    ACTIONS(64), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [52] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym_bare_string,
    ACTIONS(68), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [68] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_bare_string,
    ACTIONS(72), 7,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_bare_string,
    ACTIONS(76), 6,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_number,
      sym_boolean,
      sym_string,
      sym_raw_string,
  [99] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_key,
    STATE(16), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      aux_sym_key_token1,
      sym_string,
      sym_raw_string,
  [118] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_key,
    STATE(8), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      aux_sym_key_token1,
      sym_string,
      sym_raw_string,
  [137] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_key,
    STATE(8), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      aux_sym_key_token1,
      sym_string,
      sym_raw_string,
  [156] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_key,
    STATE(8), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      aux_sym_key_token1,
      sym_string,
      sym_raw_string,
  [175] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_key,
    STATE(17), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      aux_sym_key_token1,
      sym_string,
      sym_raw_string,
  [194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      aux_sym_key_token1,
      anon_sym_RBRACE,
      sym_string,
      sym_raw_string,
  [205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      aux_sym_key_token1,
      anon_sym_RBRACE,
      sym_string,
      sym_raw_string,
  [216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      aux_sym_key_token1,
      anon_sym_RBRACE,
      sym_string,
      sym_raw_string,
  [227] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      aux_sym_key_token1,
      anon_sym_RBRACE,
      sym_string,
      sym_raw_string,
  [238] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 5,
      ts_builtin_sym_end,
      aux_sym_key_token1,
      anon_sym_RBRACE,
      sym_string,
      sym_raw_string,
  [249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 20,
  [SMALL_STATE(10)] = 36,
  [SMALL_STATE(11)] = 52,
  [SMALL_STATE(12)] = 68,
  [SMALL_STATE(13)] = 84,
  [SMALL_STATE(14)] = 99,
  [SMALL_STATE(15)] = 118,
  [SMALL_STATE(16)] = 137,
  [SMALL_STATE(17)] = 156,
  [SMALL_STATE(18)] = 175,
  [SMALL_STATE(19)] = 194,
  [SMALL_STATE(20)] = 205,
  [SMALL_STATE(21)] = 216,
  [SMALL_STATE(22)] = 227,
  [SMALL_STATE(23)] = 238,
  [SMALL_STATE(24)] = 249,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mdl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
